#!/usr/bin/env bash
# List installed files that have been removed from the dotfiles repo

# Files that have been removed from the repo at some point
for name in $(git log --diff-filter=D --summary | grep 'delete' | cut -d' ' -f5)
do
	# Files can be re-added and still show in the list. Make sure they are not
	# currently in the repo.
	# Then check if they are installed on the system and print if so.
	if [ ! -e "$name" ] && [ -e "$HOME/$name" ]; then
		echo "$HOME/$name"
	fi
done
