#!/usr/bin/env bash
set -eu
LABEL=${LABEL:-}
CHARGING_LABEL=${CHARGING_LABEL:-$LABEL}
DISCHARGING_LABEL=${DISCHARGING_LABEL:-$LABEL}
LABEL_COLOUR=${LABEL_COLOUR:-}

# colour_fmt MSG [COLOUR]
function colour_fmt() {
	if [[ -n $2 ]]; then
		printf '<span color="%s">%s</span>' "$2" "$1"
	else
		printf '%s' "$1"
	fi
}

# msg_fmt MSG LABEL
function msg_fmt() {
	if [[ -n $2 ]]; then
		colour_fmt "$2" "$LABEL_COLOUR"
		printf ' '
	fi
	echo "$1"
}

if acpi -a | grep -q "on-line"; then
	LABEL_TEXT=$CHARGING_LABEL
	IS_CHARGING=1
else
	LABEL_TEXT=$DISCHARGING_LABEL
	IS_CHARGING=
fi

TEXT=
SHORT_TEXT=
MAX_PCT=
while read -r PERCENT TIME; do
	if [ -n "$TEXT" ]; then
		TEXT="$TEXT "
		SHORT_TEXT="$SHORT_TEXT "
	fi
	TEXT="$TEXT$PERCENT%"
	if [ -n "$TIME" ]; then
		TEXT="$TEXT ($TIME)"
	fi
	SHORT_TEXT="$SHORT_TEXT$PERCENT%"

	if [ -z "$MAX_PCT" ] || [ "$MAX_PCT" -lt "$PERCENT" ]; then
		MAX_PCT="$PERCENT"
	fi

done <<< "$(acpi -b | sed -ne 's/Battery *\([[:digit:]]\+\): *\([[:alpha:]]\+\), *\([[:digit:]]\+\)\%\(, *\([[:digit:]]\+:[[:digit:]]\+\)\)\?.*/\3 \5/p')"

msg_fmt "$TEXT" "$LABEL_TEXT"
msg_fmt "$SHORT_TEXT" "$LABEL_TEXT"
if [ -n "$MAX_PCT" ] && [ -z "$IS_CHARGING" ]; then
	if [ "$MAX_PCT" -le 5 ]; then
		echo "#FF0000"
	elif [ "$MAX_PCT" -le 15 ]; then
		echo "#FF8000"
	fi
fi
