#!/usr/bin/env bash
set -eu
OUTPUT_WIRED="$1"
OUTPUT_BATTERY="$2"
if acpi -a | grep -q 'on-line'; then
	echo "$OUTPUT_WIRED"
	echo "$OUTPUT_WIRED"
else
	echo "$OUTPUT_BATTERY"
	echo "$OUTPUT_BATTERY"
fi
