#!/usr/bin/env bash
# usage: gkrellm-toggle [NAME]
# Toggles a gkrellm instance with config suffix NAME
set -eu

RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp}/gkrellm"
mkdir -p "$RUNTIME_DIR"

if [ -n "${1:-}" ]; then
	PID_FILE_NAME="toggle-pid-$1"
	ARGS=( "-c" "$1" )
else
	PID_FILE_NAME="toggle-pid"
	ARGS=()
fi

PID_FILE="$RUNTIME_DIR/$PID_FILE_NAME"

if [ -e "$PID_FILE" ]; then
	PID=$(cat "$PID_FILE")
	# Don't want to leave PID file permanently there if the kill fails, so remove
	# first.
	rm "$PID_FILE"
	kill "$PID"
else
	mkdir -p "$RUNTIME_DIR"
	gkrellm "${ARGS[@]}" >/dev/null 2>&1 &
	echo $! > "$PID_FILE"
fi
