#!/usr/bin/env bash
# usage: gpu-usage [NUM_GPUS [WARNING_THRESHOLD [CRITICAL_THRESHOLD]]]
set -eu

NUM_GPUS=${1:-1}
WARNING_THRESHOLD=${2:-200}
ERROR_THRESHOLD=${3:-200}

for ((ID=0;ID<NUM_GPUS;ID++)); do
	PCT_USAGE="$(nvidia-smi --query-gpu=utilization.gpu --format=csv,nounits,noheader --id="$ID")"
	FG=""
	if [ "$PCT_USAGE" -ge "$ERROR_THRESHOLD" ]; then
		FG="#FF0000"
	elif [ "$PCT_USAGE" -ge "$WARNING_THRESHOLD" ]; then
		FG="#FFFC00"
	fi
	USAGE_TEXT="$PCT_USAGE%"
	if [ -n "$FG" ]; then
		USAGE_TEXT="<span foreground=\"$FG\">$USAGE_TEXT</span>"
	fi
	printf "%s" "$USAGE_TEXT"
done
printf "\n"
