#!/usr/bin/env bash
# usage: gpu-usage [ID [WARNING_THRESHOLD [CRITICAL_THRESHOLD]]]
set -eu

ID=${1:-0}
WARNING_THRESHOLD=${2:-200}
ERROR_THRESHOLD=${3:-200}

PCT_USAGE="$(nvidia-smi --query-gpu=utilization.gpu --format=csv,nounits,noheader --id="$ID")"
echo "$PCT_USAGE%"
echo "$PCT_USAGE%"
if [ "$PCT_USAGE" -ge "$ERROR_THRESHOLD" ]; then
	echo "#FF0000"
elif [ "$PCT_USAGE" -ge "$WARNING_THRESHOLD" ]; then
	echo "#FFFC00"
fi
