#!/usr/bin/env bash
set -eu

METADATA="$(pplayerctl metadata --format '{{title}} • {{artist}}' &>/dev/null)" || exit 0
case "$(pplayerctl status)" in
	Playing) ICON="▶ ";;
	Paused) ICON="⏸ ";;
	Stopped) ICON="⏹ ";;
	*) ICON="";;
esac
echo "$ICON$METADATA"
echo ""
