#!/usr/bin/env bash
set -eu

IGNORE=firefox,chromium,chrome
ARTIST="$(playerctl --ignore-player "$IGNORE" metadata artist)"
TITLE="$(playerctl --ignore-player "$IGNORE" metadata title)"
echo "$TITLE | $ARTIST"
echo ""
