#!/usr/bin/env bash
set -eu
RFKILL_WLAN_ID="$1"
OUTPUT_UNBLOCKED="$2"
OUTPUT_BLOCKED="$3"

if rfkill --output SOFT,HARD --noheadings list "$RFKILL_WLAN_ID" | \
		grep -q '\<blocked'; then
	echo "$OUTPUT_BLOCKED"
	echo "$OUTPUT_BLOCKED"
else
	echo "$OUTPUT_UNBLOCKED"
	echo "$OUTPUT_UNBLOCKED"
fi
