#!/usr/bin/env bash
set -eu
# Weather in a Canadian city.
# Weather provided by weather.gc.ca

PROVINCE_CODE="$1"
CITY_CODE="$2"
FORMAT_STR="${3:-%i  %t %s (%c)}"
SHORT_FORMAT_STR="${4:-}"

RAW_INFO=$(
	curl -s "http://weather.gc.ca/forecast/hourly/${PROVINCE_CODE}-${CITY_CODE}_metric_e.html" |
	grep 'td.*header[23]\|<title>.*24 Hour Forecast' | head -n 3)

if [ -z "$RAW_INFO" ]; then
	exit 1
fi

readarray -t RAW_INFO_LINES <<< "$RAW_INFO"

CITY=$(echo "${RAW_INFO_LINES[0]}" | sed 's/.*>\([^-]\+\) - 24 Hour Forecast.*/\1/')
TEMP=$(echo "${RAW_INFO_LINES[1]}" | sed 's/.*>\([0-9]\+\)<.*/\1/')
TEMP="$TEMP°C"
CONDITIONS=$(echo "${RAW_INFO_LINES[2]}" | sed 's/.*alt="\([^"]*\)".*/\1/')

case ${CONDITIONS,,} in
	'clear')
		ICON=🌙;;
		# ICON=☽;;
	'sunny'|'mainly sunny')
		ICON=🌣;;
		# ICON=☀;;
		# ICON=☼;;
	'partly cloudy'|'a mix of sun and cloud'|'a few clouds')
		ICON=🌤;;
		# ICON=⛅;;
	'mainly cloudy'|'mostly cloudy'|'cloudy')
		ICON=🌥;;
		# ICON=⛅;;
		# ICON=☁;;
	'light rainshower')
		ICON=🌦;;
	'light rain'|'rain'|'precipitation')
		ICON=🌨;;
		# ICON=⛈;;
	'light snow'|'snow')
		ICON=🌨;;
	'smoke')
		ICON=🔥;;
	*)
		ICON=;;
esac

FULL_TEXT="$FORMAT_STR"
FULL_TEXT="${FULL_TEXT//'%i'/$ICON}"
FULL_TEXT="${FULL_TEXT//'%t'/$TEMP}"
FULL_TEXT="${FULL_TEXT//'%s'/$CONDITIONS}"
FULL_TEXT="${FULL_TEXT//'%c'/$CITY}"
echo "$FULL_TEXT"

if [ -n "$SHORT_FORMAT_STR" ]; then
	SHORT_TEXT="$SHORT_FORMAT_STR"
	SHORT_TEXT="${SHORT_TEXT//'%i'/$ICON}"
	SHORT_TEXT="${SHORT_TEXT//'%t'/$TEMP}"
	SHORT_TEXT="${SHORT_TEXT//'%s'/$CONDITIONS}"
	SHORT_TEXT="${SHORT_TEXT//'%c'/$CITY}"
	echo "$SHORT_TEXT"
fi
