#!/usr/bin/env bash
# Wrapper around rust-analyzer that logs to ${XDG_DATA_HOME}/rust-analyzer-debug/log
set -eu

LOG_DIR="${XDG_DATA_HOME:-$HOME/.local/share}"/rust-analyzer-debug
mkdir -p "$LOG_DIR"
rust-analyzer --log-file "$LOG_DIR/log" "$@"
