#!/usr/bin/env bash
set -eu
# shellcheck source=env_utils
source "${BASH_SOURCE%/*}/env_utils"

for browser in firefox chromium google-chrome; do
	if command -v "$browser" 2>/dev/null; then
		echo "BROWSER=${browser}"
		break
	fi
done

for browser in elinks lynx; do
	if command -v "$browser" 2>/dev/null; then
		echo "TERMINAL_BROWSER=${browser}"
		break
	fi
done
