#!/usr/bin/env bash
set -eu -o pipefail
SCRIPT_DIR="$(dirname "$0")"
while read -r LINE; do
	echo "$LINE"
	VAR="${LINE%=*}"
	HEX="${LINE#*=}"
	printf "%s_DEC=%d,%d,%d\n" "$VAR" "0x${HEX:0:2}" "0x${HEX:2:2}" "0x${HEX:4:2}"
done < <(
sed -Ene '
	/^\[colors\]/,/^\[.*\]/{
		/^(color)?([[:alnum:]_]*)[[:space:]]*=[[:space:]]*"#([[:xdigit:]]+)"/{
			s//COLOUR_\U\2=\L\3/;
			p;
		};
	};
' "$SCRIPT_DIR/colours.toml"
)
