#!/usr/bin/env bash
set -eu -o pipefail
SCRIPT_DIR="$(dirname "$0")"
sed -Ene '
	/^\[colors\]/,/^\[.*\]/{
		/^(color)?([[:alnum:]_]*)[[:space:]]*=[[:space:]]*"#([[:xdigit:]]+)"/{
			s//COLOUR_\U\2=\L\3/;
			p;
		};
	};
' "$SCRIPT_DIR/colours.toml"
