#!/usr/bin/env bash
set -eu

# Get display size from xrandr so that the DPI will be correct.
# xserver lies about the DPI by default.
# https://bugs.freedesktop.org/show_bug.cgi?id=23705
# https://gitlab.freedesktop.org/xorg/xserver/issues/253
# https://pastebin.com/vtzyBK6e
read -r DISPLAY_NAME DISPLAY_WIDTH_PX DISPLAY_HEIGHT_PX DISPLAY_WIDTH_MM DISPLAY_HEIGHT_MM <<< \
	"$(xrandr | sed -ne '/^\([^ ]\+\) connected primary \([[:digit:]]\+\)x\([[:digit:]]\+\).* \([[:digit:]]\+\)mm x \([[:digit:]]\+\)mm *$/{s//\1 \2 \3 \4 \5/p;q}')"

# If there was no connected primary then try again with just the first connected
# monitor.
if [ -z "$DISPLAY_NAME" ]; then
	read -r DISPLAY_NAME DISPLAY_WIDTH_PX DISPLAY_HEIGHT_PX DISPLAY_WIDTH_MM DISPLAY_HEIGHT_MM <<< \
		"$(xrandr | sed -ne '/^\([^ ]\+\) connected \(primary \)\?\([[:digit:]]\+\)x\([[:digit:]]\+\).* \([[:digit:]]\+\)mm x \([[:digit:]]\+\)mm *$/{s//\1 \3 \4 \5 \6/p;q}')"
fi

if [ -n "$DISPLAY_NAME" ]; then
	echo "DISPLAY_NAME=$DISPLAY_NAME"
	echo "DISPLAY_DIMS=$DISPLAY_WIDTH_MM $DISPLAY_HEIGHT_MM"
	echo "DISPLAY_WIDTH_PX=$DISPLAY_WIDTH_PX"
	echo "DISPLAY_HEIGHT_PX=$DISPLAY_HEIGHT_PX"

	# True DPI
	DPI=$(( (DISPLAY_WIDTH_PX * 254) / (10 * DISPLAY_WIDTH_MM) ))
	# Unused (as of the time of this comment) but nice to have in show-config
	echo "DPI=$DPI"

	# DPI ajusted for viewer
	ADJUSTED_DPI=$DPI
	if (( DISPLAY_WIDTH_MM < 300 )); then
		# Smaller screen, assume the viewer is closer.
		ADJUSTED_DPI=$(( ADJUSTED_DPI * 3 / 4 ))
	fi

	# XFT_DPI: Used to scale fonts and other UI elements
	# Round to the nearest 96/4 = 24
	XFT_DPI=$ADJUSTED_DPI
	XFT_DPI=$(( (XFT_DPI + 12) / 24 * 24 ))
	echo "XFT_DPI=$XFT_DPI"

	# GDK_SCALE: Another way to set UI scaling
	# Setting at the same time as XFT_DPI can cause double scaling in many
	# applications so this should only be set as an environment variable
	# in isolation for applications that don't use XFT_DPI.
	# Must be an integer
	GDK_SCALE=$(( ADJUSTED_DPI / 96 ))
	if (( GDK_SCALE > 1 )); then  # Only output if != default
		echo "GDK_SCALE=$GDK_SCALE"
	fi

	# i3 max float dimensions
	echo "I3_MAX_FLOAT_WIDTH=$(( DISPLAY_WIDTH_PX * 3 / 4 ))"
	echo "I3_MAX_FLOAT_HEIGHT=$(( DISPLAY_HEIGHT_PX * 3 / 4 ))"
fi
