#!/usr/bin/env bash
set -eu

# Get display size from xrandr so that the DPI will be correct.
# xserver lies about the DPI by default.
# https://bugs.freedesktop.org/show_bug.cgi?id=23705
# https://gitlab.freedesktop.org/xorg/xserver/issues/253
# https://pastebin.com/vtzyBK6e
read -r DISPLAY_NAME DISPLAY_WIDTH_PX DISPLAY_HEIGHT_PX DISPLAY_WIDTH_MM DISPLAY_HEIGHT_MM <<< \
	"$(xrandr | sed -ne 'N;/^ *Screen 0:.*current \([[:digit:]]\+\) x \([[:digit:]]\+\).*\n\([^ ]\+\) .* \([[:digit:]]\+\)mm x \([[:digit:]]\+\)mm *$/{s//\3 \1 \2 \4 \5/p;q}')"

if [ -n "$DISPLAY_NAME" ]; then
	echo "DISPLAY_NAME=$DISPLAY_NAME"
	echo "DISPLAY_DIMS=$DISPLAY_WIDTH_MM $DISPLAY_HEIGHT_MM"
	DPI=$(( (DISPLAY_WIDTH_PX * 254) / (10 * DISPLAY_WIDTH_MM) ))
	# True DPI makes the UI too big. Scale by 3/4
	# Also scale to the nearest 24 (= 96/4)
	XFT_DPI=$(( (DPI * 3) / (4 * 24) * 24 ))
	echo "XFT_DPI=$XFT_DPI"
fi

