#!/usr/bin/env bash
set -eu

# Get display size from xrandr so that the DPI will be correct.
# xserver lies about the DPI by default.
# https://bugs.freedesktop.org/show_bug.cgi?id=23705
# https://gitlab.freedesktop.org/xorg/xserver/issues/253
# https://pastebin.com/vtzyBK6e
DISPLAY_NAME="eDP-1"
read -r EDP_WIDTH_PX EDP_HEIGHT_PX EDP_WIDTH_MM EDP_HEIGHT_MM <<< \
	"$(xrandr | grep "$DISPLAY_NAME" -B1 | sed -ne 'N;s/.*current \([[:digit:]]\+\) x \([[:digit:]]\+\).* \([[:digit:]]\+\)mm x \([[:digit:]]\+\)mm *$/\1 \2 \3 \4/p')"

if [ -n "$EDP_WIDTH_MM" ]; then
	echo "DISPLAY_NAME=$DISPLAY_NAME"
	echo "DISPLAY_DIMS=$EDP_WIDTH_MM $EDP_HEIGHT_MM"
	DPI=$(( (EDP_WIDTH_PX * 254) / (10 * EDP_WIDTH_MM) ))
	# True DPI makes the UI too big. Scale by 3/4
	# Also scale to the nearest 24 (= 96/4)
	XFT_DPI=$(( (DPI * 3) / (4 * 24) * 24 ))
	echo "XFT_DPI=$XFT_DPI"
fi

