#!/bin/bash
set -eu
# shellcheck source=env_utils
source "${BASH_SOURCE%/*}/env_utils"

if find_program I3 i3; then
	I3_VERSION="$(i3 --version)"
	if version_ge "$I3_VERSION" "i3 version 4.15"; then
		echo I3_CONFIG_EDGE_BORDERS=smart
	fi
fi
