#!/usr/bin/env bash
set -eu
source "${BASH_SOURCE%/*}/env_utils"

if find_program I3BLOCKS i3blocks; then
	find_directory I3BLOCKS_DIR \
		"$HOME/libexec/i3blocks" \
		"$HOME/.local/libexec/i3blocks" \
		"/usr/lib/i3blocks" \
		"/usr/share/i3blocks" \
		"/usr/local/libexec/i3blocks" \
		|| true
fi
