#!/bin/bash
set -eu
source "${BASH_SOURCE%/*}/env_utils"

# Prefer xscreensaver if present
if XSCREENSAVER="$(command -v xscreensaver 2>/dev/null)"; then
	if command -v xdg-screensaver >/dev/null 2>&1; then
		MANUAL_LOCK_CMD="xdg-screensaver lock"
	else
		MANUAL_LOCK_CMD="xscreensaver-command -l"
	fi
	ENABLE_LOCKER_CMD="$XSCREENSAVER -nosplash"
	echo "MANUAL_LOCK_CMD=$MANUAL_LOCK_CMD"
	echo "ENABLE_LOCKER_CMD=$ENABLE_LOCKER_CMD"
	exit 0
fi

# Otherwise use xsecurelock
if XSECURELOCK="$(command -v xsecurelock 2>/dev/null)"; then
	LOCK_CMD="$XSECURELOCK"
	if [ -f "/usr/lib/xsecurelock/dimmer" ]; then
		DIMMER="/usr/lib/xsecurelock/dimmer"
	else
		DIMMER=""
	fi
fi
MANUAL_LOCK_CMD="$LOCK_CMD"

if XSS_LOCK="$(command -v xss-lock 2>/dev/null)"; then
	XSS_ARGS=()
	if [ -n "$DIMMER" ]; then
		XSS_ARGS+=('-n' "$DIMMER")
	fi
	ENABLE_LOCKER_CMD="xset s 300 5;$XSS_LOCK ${XSS_ARGS[@]} -- $LOCK_CMD"
	# XSS LOCK watches for screen suspend and triggers a lock
	MANUAL_LOCK_CMD="xset dpms force suspend"
fi

echo "MANUAL_LOCK_CMD=$MANUAL_LOCK_CMD"
echo "ENABLE_LOCKER_CMD=$ENABLE_LOCKER_CMD"
