#!/usr/bin/env bash
set -eu
source "${BASH_SOURCE%/*}/env_utils"

find_program MODULECMD modulecmd || exit 0

MODULE_VERSION="$(modulecmd bash -V 2>&1 | grep -ow '[.0-9]\+' | head -n1)"
if version_ge "$MODULE_VERSION" "4.0.0"; then
  echo MODULE_GE_4=
fi;

# Find the module command initialization directory.
# Needed if autoinit is unavailable.
find_directory MODULE_INIT_DIR \
	"${DATA_DIR}/modules/init" \
	"/usr/share/modules/init" \
	|| true

# Find the default collection to import immediately
find_file MODULE_DEFAULT_COLLECTION \
	"${CONFIG_DIR}/modules/default" \
	"$HOME/.module/default" \
	|| true
