#!/usr/bin/env bash
set -eu
source "${BASH_SOURCE%/*}/env_utils"

find_directory MUJOCO_PATH "$HOME/.local/share/mujoco/mujoco200_linux" || true
find_file MJKEY_PATH "$HOME/.local/share/mujoco/mjkey.txt" || true
