#!/usr/bin/env bash
# Simple checks for installed programms
set -eu
# shellcheck source=env_utils
source "${BASH_SOURCE%/*}/env_utils"

find_program DEX dex || true
find_program DIRENV direnv || true
find_program DMENU j4-dmenu-desktop i3-dmenu-desktop dmenu_run || true
find_program FEH feh || true
find_program GRADLE gradle || true
find_program GRIP grip || true
find_program GSIMPLECAL gsimplecal || true
find_program I3BLOCKS i3blocks || true
find_program IP_CMD ip || true
find_program MAIM maim || true
find_program PICOM picom || true
find_program PLAYERCTL playerctl || true
find_program PULSEAUDIO pulseaudio || true
find_program RLWRAP rlwrap || true
find_program SETXKBMAP setxkbmap || true
find_program SHELL fish || true
find_program SYSTEMCTL systemctl || true
find_program TASK task || true
find_program TERMINAL alacritty terminator termite gnome-terminal xterm || true
find_program WINE wine || true
# Install acpilight for xbacklight
find_program XBACKLIGHT xbacklight || true
find_program XBINDKEYS xbindkeys || true
find_program XDOTOOL xdotool || true
find_program XMODMAP xmodmap || true
find_program ZOOM zoom || true
