#!/usr/bin/env bash
# Simple checks for installed programms
set -eu
# shellcheck source=env_utils
source "${BASH_SOURCE%/*}/env_utils"

find_program AWS aws || true
find_program BRIGHTNESSCTL brightnessctl || true
find_program CONDA conda || true
find_program DEX dex || true
find_program DIRENV direnv || true
find_program DMENU j4-dmenu-desktop i3-dmenu-desktop dmenu_run || true
find_program DOCKER docker || true
find_program FEH feh || true
find_program GRADLE gradle || true
find_program GRIP grip || true
find_program GSIMPLECAL gsimplecal || true
find_program I3BLOCKS i3blocks || true
find_program IP_CMD ip || true
find_program MAIM maim || true
find_program NODE node || true
find_program PICOM picom || true
find_program PLAYERCTL playerctl || true
find_program PULSEAUDIO pulseaudio || true
find_program PYTHON_ARGCOMPLETE register-python-argcomplete || true
find_program RLWRAP rlwrap || true
find_program SETXKBMAP setxkbmap || true
find_program SHELL fish bash || true
find_program SQLITE sqlite3 || true
find_program STACK stack || true
find_program SYSTEMCTL systemctl || true
find_program TASK task || true
find_program TERMINAL alacritty terminator termite gnome-terminal xterm || true
find_program TIMETRACE timetrace || true
find_program WINE wine || true
# Install acpilight for xbacklight
find_program XBACKLIGHT xbacklight || true
find_program XBINDKEYS xbindkeys || true
find_program XDOTOOL xdotool || true
find_program XLSCLIENTS xlsclients || true
find_program XMODMAP xmodmap || true
find_program ZOOM zoom || true
