#!/usr/bin/env bash
set -eu
# shellcheck source=env_utils
source "${BASH_SOURCE%/*}/env_utils"

find_program PYTHON2 python2 || true
find_program PYTHON3 python3 || true
find_program PYTHON python || true
