#!/bin/bash
set -eu
# shellcheck source=env_utils
source "${BASH_SOURCE%/*}/env_utils"

find_program CARGO cargo "${DATA_DIR}/cargo/bin/cargo" || true

# Binaries managed by cargo / rustup
find_directory CARGO_BIN "${DATA_DIR}/cargo/bin" || true
