#!/bin/bash
set -eu
source "${BASH_SOURCE%/*}/env_utils"

TMUX_VERSION="$(tmux -V)"
if version_ge "$TMUX_VERSION" "tmux 2.0"; then
	echo TMUX_GE_2_0=
fi;
if version_ge "$TMUX_VERSION" "tmux 2.2"; then
	echo TMUX_GE_2_2=
fi;
