#!/bin/bash
set -eu
# shellcheck source=env_utils
source "${BASH_SOURCE%/*}/env_utils"

find_file TORCH_ACTIVATE\
	"$HOME/torch/install/bin/torch-activate" \
	"$HOME/src/torch/install/bin/torch-activate"
