#!/bin/bash
set -eu
# Search in $HOME/{,programs,src}/torch
TORCH_ACTIVATE=$(ls $HOME/{,programs,src/}torch/install/bin/torch-activate 2>/dev/null | head -n 1)
if [ -n "$TORCH_ACTIVATE" ]; then
	echo TORCH_ACTIVATE=$TORCH_ACTIVATE
fi
