#!/usr/bin/env bash
# Simple checks for desirable programs
# Unlike `programs`, these are not used for configuration.
set -eu
# shellcheck source=env_utils
source "${BASH_SOURCE%/*}/env_utils"

echo "# Python linting"
find_program FLAKE8 flake8 || true
echo "# Reorder python imports; used automatically by ALE"
find_program ISORT isort || true
echo "# Fast code search"
find_program THE_SILVER_SEARCHER ag || true
echo "# Shell script analysis tool; used automatically by ALE"
find_program SHELLCHECK shellcheck || true

LOGIN_DEFS_FILE="/etc/login.defs"
if [ -f "$LOGIN_DEFS_FILE" ]; then
	FAIL_DELAY="$(sed -n '/^[[:space:]]*FAIL_DELAY[[:space:]]*\([[:digit:]]*\)[[:space:]]*$/{s//\1/;p;q}' "$LOGIN_DEFS_FILE")"
	echo "# Login password fail delay; set to 1 in $LOGIN_DEFS_FILE"
	echo "FAIL_DELAY=$FAIL_DELAY"
fi

PICOM_FILE="$HOME/.config/picom.conf"
if ! [ -f "$PICOM_FILE" ]; then
	PICOM_FILE="/etc/xdg/picom.conf"
fi
if [ -f "$PICOM_FILE" ]; then
	echo "# Picom; set shadow=false and fading=false"
	SHADOW="$(sed -n '/^[[:space:]]*fading[[:space:]]*=[[:space:]]*\([[:alpha:]]*\)[[:space:]]*;/{s//\1/;p;q}' "$PICOM_FILE")"
	echo "PICOM_SHADOW=$SHADOW"
	FADING="$(sed -n '/^[[:space:]]*fading[[:space:]]*=[[:space:]]*\([[:alpha:]]*\)[[:space:]]*;/{s//\1/;p;q}' "$PICOM_FILE")"
	echo "PICOM_FADING=$FADING"
fi
