#!/usr/bin/env bash
# List installed files that have been removed from the dotfiles repo

# Files that have been removed from the repo at some point
{
for name in $(git log --diff-filter=D --summary | grep 'delete' | cut -d' ' -f5)
do
	# Files can be re-added and still show in the list. Make sure they are not
	# currently in the repo. Other files have the .m4 suffix remove so make sure
	# they do not appear either.
	if [ ! -e "$name" ] && [ ! -e "${name%.m4}" ] ; then
		installname="$HOME/${name%.m4}"
		if [ -e "$installname" ]; then
			echo "$installname"
		fi
	fi
done
} | sort | uniq
