#!/bin/bash
set -eu

dmenu_preferences=( j4-dmenu-desktop i3-dmenu-desktop dmenu_run )

# Find a preferred dmenu
for dmenu in "${dmenu_preferences[@]}"; do
	if hash "${dmenu}" 2>/dev/null; then
		echo "DMENU=$(which ${dmenu})"
		exit 0
	fi
done

exit 0
