#!/usr/bin/env bash
set -eu

if command -v i3blocks >/dev/null 2>&1; then
	echo "I3BLOCKS="
	possible_i3blocks_dirs=( \
		"$HOME/libexec/i3blocks" \
		"$HOME/.local/libexec/i3blocks" \
		"/usr/lib/i3blocks" \
		"/usr/share/i3blocks" \
		"/usr/local/libexec/i3blocks" \
		)

	for i3blocks_dir in "${possible_i3blocks_dirs[@]}"; do
		if [ -d "${i3blocks_dir}" ]; then
			echo "I3BLOCKS_DIR=${i3blocks_dir}"
			exit 0
		fi
	done
fi
