#!/bin/bash
set -eu
if hash i3lock-extra 2>/dev/null; then
	if i3lock-extra --help | grep -e '--paint' &>/dev/null; then
		echo "I3LOCK_CMD=i3lock-extra -s -p --paint --unsecure -- -e"
	else
		echo "I3LOCK_CMD=i3lock-extra -s -p --unsecure -- -e"
	fi
else
	echo "I3LOCK_CMD=i3lock -c 000000 -e"
fi
