#!/bin/bash
set -eu
if hash i3lock-extra 2>/dev/null; then
	CMD="i3lock-extra -s -p --unsecure"
	if i3lock-extra --help | grep -e '--paint' &>/dev/null; then
		CMD+=" --paint"
	fi
	CMD+=" --"
else
	CMD="i3lock -c 500000"
fi
if i3lock -h 2>&1 | grep '\[-e\]' &>/dev/null; then
	CMD+=" -e"
fi
echo "LOCK_CMD=$CMD"
