#!/bin/bash
set -eu
source "${BASH_SOURCE%/*}/env_utils"

# Prefer xscreensaver if present
if XSCREENSAVER="$(command -v xscreensaver 2>/dev/null)"; then
	echo "START_SCREENSAVER=$XSCREENSAVER -nosplash"
	if command -v xdg-screensaver >/dev/null 2>&1; then
		echo "LOCK_CMD=xdg-screensaver lock"
	else
		echo "LOCK_CMD=xscreensaver-command -l"
	fi
	exit 0
fi

# Otherwise use i3lock & xss-lock
find_program XSS_LOCK xss-lock || true

USING_I3LOCK=0
if XSECURELOCK="$(command -v xsecurelock 2>/dev/null)"; then
	CMD="$XSECURELOCK"
elif program_exists i3lock-extra; then
	CMD="i3lock-extra -s -p"
	if i3lock-extra --help | grep -e '--paint' &>/dev/null; then
		CMD+=" --paint"
	fi
	CMD+=" --"
	USING_I3LOCK=1
else
	CMD="i3lock -c 000000"
	USING_I3LOCK=1
fi
if [ "$USING_I3LOCK" -eq 1 ] && i3lock -h 2>&1 | grep '\[-e\]' &>/dev/null; then
	CMD+=" -e"
fi
echo "LOCK_CMD=$CMD"
