#!/usr/bin/env bash
# Simple checks for installed programms
set -eu
source "${BASH_SOURCE%/*}/env_utils"

find_installed DMENU j4-dmenu-desktop i3-dmenu-desktop dmenu_run || true
find_installed FEH feh || true
find_installed GSIMPLECAL gsimplecal || true
find_installed IP_CMD ip || true
find_installed KEYCHAIN keychain || true
find_installed PLAYERCTL playerctl || true
find_installed PULSEAUDIO pactl || true
find_installed SETXKBMAP setxkbmap || true
find_installed SHELL fish || true
find_installed TASK task || true
find_installed TERMINAL terminator termite gnome-terminal xterm || true
find_installed XBACKLIGHT xbacklight || true
find_installed XBINDKEYS xbindkeys || true
find_installed XDOTOOL xdotool || true
find_installed XINPUT xinput || true
find_installed XMODMAP xmodmap || true
