#!/usr/bin/env bash
set -eu

if command -v gsort >/dev/null 2>&1; then
	sortcmd=gsort
else
	sortcmd=sort
fi

if PYTHON2="$(command -v python2 2>/dev/null)"; then
	echo "PYTHON2=$PYTHON2"
fi;

if PYTHON3="$(command -v python3 2>/dev/null)"; then
	echo "PYTHON3=$PYTHON3"
fi;

if PYTHON="$(command -v python 2>/dev/null)"; then
	echo "PYTHON=$PYTHON"
fi;

if echo -e Python 3"\n"$(python --version 2>&1) | ${sortcmd} -V --check=quiet; then
	echo USING_PYTHON3=
fi
