#!/usr/bin/env bash
set -eu

if hash gsort &>/dev/null; then
	sortcmd=gsort
else
	sortcmd=sort
fi

if hash python2 2>/dev/null; then
	echo PYTHON2=$(which python2)
fi;

if hash python3 2>/dev/null; then
	echo PYTHON3=$(which python3)
fi;

if hash python 2>/dev/null; then
	echo PYTHON=$(which python)
fi;

if echo -e Python 3"\n"$(python --version 2>&1) | ${sortcmd} -V --check=quiet; then
	echo USING_PYTHON3=
fi
