#!/usr/bin/env bash
set -eu
source "${BASH_SOURCE%/*}/env_utils"

find_program PYTHON2 python2 || true
find_program PYTHON3 python3 || true
find_program PYTHON python

if version_ge "$(python --version 2>&1)" "Python 3"; then
	echo USING_PYTHON3=
fi
