#!/bin/bash
set -eu
if hash gem 2>/dev/null; then
	GEM_BIN_PATH=$(gem environment gempath | tr ':' '\n' | sed 's#$#/bin#' | xargs ls -d 2>/dev/null | paste -sd':' -)
	if [ -n "$GEM_BIN_PATH" ]; then
		echo GEM_BIN_PATH=$GEM_BIN_PATH
	fi
fi
