#!/usr/bin/env bash
# System monitor
set -eu

if command -v netdata 2>/dev/null; then
	NETDATA_POPUP="xdg-open http://localhost:19999"
	echo I3BLOCKS_CPU_POPUP="$NETDATA_POPUP"
	echo I3BLOCKS_MEM_POPUP="$NETDATA_POPUP"
	exit
fi

I3BLOCKS_SCRIPTS="${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/scripts"
if command -v conky 2>/dev/null; then
	CONKY_POPUP="$I3BLOCKS_SCRIPTS/conky-toggle"
	echo I3BLOCKS_CPU_POPUP="$CONKY_POPUP"
	echo I3BLOCKS_MEM_POPUP="$CONKY_POPUP"
	exit
fi

if command -v gkrellm 2>/dev/null; then
	GKRELLM_POPUP="$I3BLOCKS_SCRIPTS/gkrellm-toggle"
	echo I3BLOCKS_CPU_POPUP="$GKRELLM_POPUP cpu"
	echo I3BLOCKS_MEM_POPUP="$GKRELLM_POPUP mem"
	exit
fi
