#!/bin/bash
set -eu

terminal_preferences=( termite terminator gnome-terminal xterm )

# Find a preferred terminal
for terminal in "${terminal_preferences[@]}"; do
	if hash "${terminal}" 2>/dev/null; then
		echo "TERMINAL=$(which ${terminal})"
		exit 0
	fi
done

exit 0
